import {
  ATTACK_COOLDOWN_MS,
  ATTACK_DURATION_MS,
  BODY_HEIGHT,
  BODY_OFFSET_X,
  BODY_OFFSET_Y,
  BODY_WIDTH,
  DAMAGE,
  DETECT_RANGE_PX,
  FOLLOW_OFFSET_X,
  FOLLOW_OFFSET_Y,
  HITBOX_H,
  HITBOX_OFFSET_X,
  HITBOX_W,
  MOCHI_TEXTURE_ATTACK,
  MOCHI_TEXTURE_IDLE,
} from './constants.js';

/** @type {import('../sidekickTypes.js').SidekickConfig} */
export const SIDEKICK_CONFIG = {
  id: 'mochi_axolotl',
  displayName: 'Mochi',
  tagline: 'Axolotl squire',
  weaponLine: 'Candy thermometer mallet',
  textureIdle: MOCHI_TEXTURE_IDLE,
  textureAttack: MOCHI_TEXTURE_ATTACK,
  followOffsetX: FOLLOW_OFFSET_X,
  followOffsetY: FOLLOW_OFFSET_Y,
  attackCooldownMs: ATTACK_COOLDOWN_MS,
  attackDurationMs: ATTACK_DURATION_MS,
  detectRangePx: DETECT_RANGE_PX,
  hitboxW: HITBOX_W,
  hitboxH: HITBOX_H,
  hitboxOffsetX: HITBOX_OFFSET_X,
  damage: DAMAGE,
  bodyWidth: BODY_WIDTH,
  bodyHeight: BODY_HEIGHT,
  bodyOffsetX: BODY_OFFSET_X,
  bodyOffsetY: BODY_OFFSET_Y,
  displayScale: 1.08,
};
